spring.application.name=order-service

#DB Configuration
spring.datasource.url =jdbc:postgresql://localhost:5432/ordersDb
spring.datasource.username=postgres
spring.datasource.password=0000
#spring.jpa.hibernate.ddl-auto=none

server.port = 7088

server.servlet.context-path =/orders
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.defer-datasource-initialization = true
#spring.sql.init.mode = always
#spring.sql.init.data-locations=classpath:data.sql

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
eureka.instance.prefer-ip-address=true

