spring.application.name=inventory-service

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=7089
server.servlet.context-path=/inventory

#spring.jpa.defer-datasource-initialization = true
#spring.sql.init.mode = always
#spring.sql.init.data-locations=classpath:data.sql


#eureka config
#eureka.client.service-url.defaultZone=http:localhost:8085/eureka
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
eureka.instance.prefer-ip-address=true

